"""add title and location_name to posts

Revision ID: 1b1c0f49e85b
Revises: 2d2a927b6e0a
Create Date: 2026-09-21 14:27:33.406872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1c0f49e85b'
down_revision: Union[str, Sequence[str], None] = '2d2a927b6e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('location_name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'location_name')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
