"""add utm_source to post_shares

Revision ID: 23de5a57da86
Revises: 270251483fa7
Create Date: 2026-09-21 15:11:02.375906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23de5a57da86'
down_revision: Union[str, Sequence[str], None] = '270251483fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_shares', sa.Column('utm_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_shares', 'utm_source')
    # ### end Alembic commands ###
