"""add likes comments and shares counters to posts

Revision ID: 270251483fa7
Revises: 1b1c0f49e85b
Create Date: 2026-09-21 15:03:06.017922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270251483fa7'
down_revision: Union[str, Sequence[str], None] = '1b1c0f49e85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('posts', sa.Column('comments_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('posts', sa.Column('shares_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE posts
        SET likes_count = counts.total
        FROM (SELECT post_id, count(*) AS total FROM post_likes GROUP BY post_id) AS counts
        WHERE posts.id = counts.post_id
        """
    )
    op.execute(
        """
        UPDATE posts
        SET comments_count = counts.total
        FROM (
            SELECT post_id, count(*) AS total
            FROM post_comments
            WHERE deleted_at IS NULL
            GROUP BY post_id
        ) AS counts
        WHERE posts.id = counts.post_id
        """
    )
    op.execute(
        """
        UPDATE posts
        SET shares_count = counts.total
        FROM (SELECT post_id, count(*) AS total FROM post_shares GROUP BY post_id) AS counts
        WHERE posts.id = counts.post_id
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'shares_count')
    op.drop_column('posts', 'comments_count')
    op.drop_column('posts', 'likes_count')
    # ### end Alembic commands ###
