"""create user settings tables

Revision ID: 3ccf1dfde574
Revises: 0fb7dcd6a2c1
Create Date: 2026-09-22 19:57:47.181101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3ccf1dfde574'
down_revision: Union[str, Sequence[str], None] = '0fb7dcd6a2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ai_response_style_enum = postgresql.ENUM(
    'concise', 'balanced', 'detailed', name='ai_response_style', create_type=False
)
visibility_level_enum = postgresql.ENUM(
    'public', 'followers', 'private', name='visibility_level', create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    ai_response_style_enum.create(bind, checkfirst=True)
    visibility_level_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ai_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('personalization_enabled', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('response_style', ai_response_style_enum, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_content_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_filter', sa.String(length=10), nullable=True),
    sa.Column('hide_sensitive_content', sa.Boolean(), nullable=False),
    sa.Column('personalized_feed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('post_activity', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.Boolean(), nullable=False),
    sa.Column('likes', sa.Boolean(), nullable=False),
    sa.Column('mentions', sa.Boolean(), nullable=False),
    sa.Column('followers', sa.Boolean(), nullable=False),
    sa.Column('messages', sa.Boolean(), nullable=False),
    sa.Column('ai_updates', sa.Boolean(), nullable=False),
    sa.Column('system_updates', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_privacy_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile_visibility', visibility_level_enum, nullable=False),
    sa.Column('location_visibility', visibility_level_enum, nullable=False),
    sa.Column('activity_visibility', visibility_level_enum, nullable=False),
    sa.Column('allow_messages', sa.Boolean(), nullable=False),
    sa.Column('allow_mentions', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_content_preferred_districts',
    sa.Column('user_content_settings_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['gis_districts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_content_settings_id'], ['user_content_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_content_settings_id', 'district_id')
    )
    op.create_table('user_content_preferred_tags',
    sa.Column('user_content_settings_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_content_settings_id'], ['user_content_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_content_settings_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_content_preferred_tags')
    op.drop_table('user_content_preferred_districts')
    op.drop_table('user_settings')
    op.drop_table('user_privacy_settings')
    op.drop_table('user_notification_settings')
    op.drop_table('user_content_settings')
    op.drop_table('user_ai_settings')
    # ### end Alembic commands ###

    bind = op.get_bind()
    visibility_level_enum.drop(bind, checkfirst=True)
    ai_response_style_enum.drop(bind, checkfirst=True)
