"""add soft delete, user type, and profile image to users

Revision ID: 69a165a4120c
Revises: 623c048abc61
Create Date: 2026-09-17 13:33:20.493492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a165a4120c'
down_revision: Union[str, Sequence[str], None] = '623c048abc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_type_enum = sa.Enum('customer', 'admin', name='user_type')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=2048), nullable=True))
    op.add_column(
        'users',
        sa.Column('user_type', user_type_enum, nullable=False, server_default='customer'),
    )
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.create_index('ix_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_users_phone_active', 'users', ['phone'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_phone_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'profile_image_url')
    user_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
