"""create posts post_media post_comments post_likes and post_shares tables

Revision ID: edfc0e7b0bc4
Revises: 1eb9c7377289
Create Date: 2026-09-21 13:14:46.089279

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfc0e7b0bc4'
down_revision: Union[str, Sequence[str], None] = '1eb9c7377289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', name='post_status'), nullable=False),
    sa.Column('location', geoalchemy2.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_deleted_at', 'posts', ['deleted_at'], unique=False)
    op.create_index('ix_posts_status', 'posts', ['status'], unique=False)
    op.create_index('ix_posts_user_id', 'posts', ['user_id'], unique=False)
    op.create_index('ix_posts_location', 'posts', ['location'], unique=False, postgresql_using='gist')
    op.create_table('post_comments',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_comments_parent_id', 'post_comments', ['parent_id'], unique=False)
    op.create_index('ix_post_comments_post_id', 'post_comments', ['post_id'], unique=False)
    op.create_index('ix_post_comments_user_id', 'post_comments', ['user_id'], unique=False)
    op.create_table('post_likes',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_likes_post_id_user_id')
    )
    op.create_index('ix_post_likes_post_id', 'post_likes', ['post_id'], unique=False)
    op.create_index('ix_post_likes_user_id', 'post_likes', ['user_id'], unique=False)
    op.create_table('post_media',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='post_media_type'), nullable=False),
    sa.Column('file_url', sa.String(length=2048), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_media_post_id', 'post_media', ['post_id'], unique=False)
    op.create_table('post_shares',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_shares_post_id', 'post_shares', ['post_id'], unique=False)
    op.create_index('ix_post_shares_user_id', 'post_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_shares_user_id', table_name='post_shares')
    op.drop_index('ix_post_shares_post_id', table_name='post_shares')
    op.drop_table('post_shares')
    op.drop_index('ix_post_media_post_id', table_name='post_media')
    op.drop_table('post_media')
    op.drop_index('ix_post_likes_user_id', table_name='post_likes')
    op.drop_index('ix_post_likes_post_id', table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_index('ix_post_comments_user_id', table_name='post_comments')
    op.drop_index('ix_post_comments_post_id', table_name='post_comments')
    op.drop_index('ix_post_comments_parent_id', table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index('ix_posts_location', table_name='posts', postgresql_using='gist')
    op.drop_index('ix_posts_user_id', table_name='posts')
    op.drop_index('ix_posts_status', table_name='posts')
    op.drop_index('ix_posts_deleted_at', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
